In [ ]:
import pandas as pd

file_name = "ifn619_class_2026.csv"
class_df = pd.read_csv(f"data/{file_name}", index_col="id")
class_df.shape

(228, 2)

In [6]:
class_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 228 entries, 1001 to 1228
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   course  228 non-null    object
 1   mode    228 non-null    object
dtypes: object(2)
memory usage: 5.3+ KB

In [8]:
class_df.describe()

       course mode
count     228  228
unique      6    3
top       MDS   FT
freq      144  185

In [4]:
class_df

     course mode
id
1001    MIT   PT
1002    MDS   FP
1003    MDS   FT
1004    MIT   FT
1005    MDS   FP
...     ...  ...
1224    MDS   FT
1225    MDS   FT
1226    MDS   FT
1227   GCDS   FT
1228    MIT   FT

[228 rows x 2 columns]

In [10]:
pd.set_option("display.max_rows", None)
class_df

     course mode
id
1001    MIT   PT
1002    MDS   FP
1003    MDS   FT
1004    MIT   FT
1005    MDS   FP
1006    MDS   FT
1007  Other   FT
1008    MIT   PT
1009    MDS   PT
1010    MDS   FT
1011    MDS   FT
1012    MDS   FT
1013  Other   PT
1014    MIT   PT
1015    MDS   FT
1016    MDA   FT
1017    MIT   FT
1018    MDS   FT
1019    MDS   FT
1020    MDS   FT
1021    MIT   FT
1022    MIT   FT
1023    MDS   FT
1024    MDA   FT
1025    MIT   FT
1026    MDS   FT
1027    MIT   FT
1028    MIT   FT
1029    MDS   FT
1030  Other   FT
1031    MIT   FT
1032    MDA   FT
1033    MIT   PT
1034    MIT   FT
1035    MDS   FT
1036    MDS   FT
1037    MIT   FT
1038    MAI   FT
1039    MIT   FT
1040    MIT   PT
1041    MIT   FT
1042    MDS   FT
1043    MIT   FT
1044    MIT   FT
1045    MIT   FT
1046    MIT   FT
1047    MIT   FT
1048    MDS   FT
1049    MIT   FT
1050    MDS   FT
1051  Other   FT
1052    MIT   FT
1053    MIT   FT
1054    MDS   FT
1055    MDS   FT
1056    MDS   FT
1057    MDS   FT
1058  Other   FT
1059    MIT   FT
1060    MDS   FT
1061    MIT   FT
1062    MDS   FT
1063    MDS   FT
1064    MDS   FT
1065    MDS   FT
1066    MDS   FT
1067    MDS   FT
1068    MDS   FT
1069    MDS   FP
1070    MDS   FT
1071    MDS   FT
1072    MDS   FT
1073    MDS   FT
1074    MDS   FT
1075    MDS   FT
1076    MDS   FT
1077    MDS   FT
1078    MDS   FT
1079    MDS   FT
1080    MIT   FT
1081    MDS   FT
1082    MDS   FT
1083    MDS   FT
1084    MDS   FT
1085    MDS   FT
1086    MDS   FT
1087    MDS   FT
1088    MIT   FT
1089    MDS   FT
1090    MDS   FT
1091    MDS   FT
1092    MDS   FT
1093   GCDS   PT
1094    MDS   FT
1095    MDS   FT
1096    MDS   FT
1097    MDS   FT
1098    MDS   FT
1099    MDS   FT
1100    MDS   FT
1101    MDS   FT
1102    MDS   FT
1103    MDS   FT
1104    MDS   FT
1105    MDS   FT
1106    MDS   FT
1107    MDS   FT
1108    MDS   FT
1109    MDS   FT
1110    MDS   FT
1111   GCDS   FT
1112    MDS   FT
1113    MDS   FT
1114    MDS   FT
1115    MDS   FT
1116    MAI   FT
1117    MDS   FT
1118    MDS   FT
1119    MAI   FT
1120    MDS   FT
1121    MDS   FT
1122    MDS   FT
1123    MDS   FT
1124    MDS   FT
1125    MDS   FT
1126   GCDS   FT
1127    MDS   PT
1128   GCDS   PT
1129   GCDS   FT
1130   GCDS   PT
1131    MDS   PT
1132    MDS   FP
1133    MIT   FT
1134  Other   FT
1135    MDS   FT
1136    MDS   FT
1137    MDS   PT
1138    MDS   PT
1139    MDS   FT
1140    MIT   FT
1141   GCDS   PT
1142    MDA   PT
1143    MIT   FT
1144    MIT   FT
1145    MIT   FT
1146    MIT   FT
1147    MDS   FT
1148    MAI   FT
1149    MDA   FT
1150    MDS   FT
1151    MDS   FP
1152    MIT   FT
1153    MIT   FT
1154    MIT   FT
1155    MIT   FT
1156    MIT   PT
1157    MIT   FT
1158    MIT   PT
1159    MDS   PT
1160    MIT   FT
1161    MDS   FT
1162    MDS   FT
1163    MIT   FT
1164    MIT   FT
1165    MDS   FT
1166    MDS   FT
1167    MDS   FT
1168    MDS   PT
1169    MDS   PT
1170    MDS   FT
1171    MDS   FT
1172    MDS   PT
1173  Other   FT
1174    MDS   FT
1175    MDS   FT
1176    MDS   FT
1177    MDS   FP
1178    MDS   FP
1179    MIT   FT
1180    MDS   FT
1181    MDS   FT
1182    MDS   FP
1183   GCDS   PT
1184    MDS   FT
1185    MDS   FT
1186    MDS   FP
1187    MIT   FT
1188    MDS   FT
1189    MDS   FT
1190   GCDS   FT
1191    MDS   FT
1192   GCDS   PT
1193    MDS   FT
1194    MDS   PT
1195    MDS   FT
1196    MDS   FT
1197    MDS   FT
1198    MDS   FT
1199  Other   PT
1200    MDA   FT
1201    MDA   FP
1202   GCDS   FP
1203    MDS   PT
1204    MDS   FT
1205    MDS   FP
1206    MDS   FT
1207    MDS   FT
1208   GCDS   PT
1209    MDS   FT
1210  Other   FT
1211    MDS   FT
1212    MIT   FT
1213    MDS   FT
1214    MIT   PT
1215    MIT   FT
1216    MDS   FT
1217    MDS   FT
1218    MDS   FT
1219    MDS   FT
1220    MDS   FT
1221    MDS   FT
1222    MDS   FP
1223    MDS   FP
1224    MDS   FT
1225    MDS   FT
1226    MDS   FT
1227   GCDS   FT
1228    MIT   FT

In [11]:
class_df.groupby("course").size()

course
GCDS      13
MAI        4
MDA        7
MDS      144
MIT       51
Other      9
dtype: int64

In [12]:
course_totals_df = class_df.groupby("course").size().reset_index(name="cohort_size")
course_totals_df

  course  cohort_size
0   GCDS           13
1    MAI            4
2    MDA            7
3    MDS          144
4    MIT           51
5  Other            9

In [13]:
course_totals_df.describe()

       cohort_size
count     6.000000
mean     38.000000
std      54.750342
min       4.000000
25%       7.500000
50%      11.000000
75%      41.500000
max     144.000000

In [15]:
import plotly.express as px

fig = px.bar(course_totals_df, x="course", y="cohort_size", width=600, height=400)
fig.show()

In [16]:
sorted_df = course_totals_df.sort_values(by="cohort_size", ascending=False)
sorted_df

  course  cohort_size
3    MDS          144
4    MIT           51
0   GCDS           13
5  Other            9
2    MDA            7
1    MAI            4

In [17]:
fig = px.bar(sorted_df, x="course", y="cohort_size", width=600, height=400)
fig.show()

In [18]:
class_df.groupby(["course", "mode"]).size()

course  mode
GCDS    FP        1
        FT        5
        PT        7
MAI     FT        4
MDA     FP        1
        FT        5
        PT        1
MDS     FP       12
        FT      121
        PT       11
MIT     FT       43
        PT        8
Other   FT        7
        PT        2
dtype: int64

In [20]:
course_mode_df = class_df.groupby(["course", "mode"]).size().reset_index(name="course_mode")
course_mode_df

   course mode  course_mode
0    GCDS   FP            1
1    GCDS   FT            5
2    GCDS   PT            7
3     MAI   FT            4
4     MDA   FP            1
5     MDA   FT            5
6     MDA   PT            1
7     MDS   FP           12
8     MDS   FT          121
9     MDS   PT           11
10    MIT   FT           43
11    MIT   PT            8
12  Other   FT            7
13  Other   PT            2

In [22]:
fig2 = px.bar(course_mode_df, x="course", y="course_mode", color="mode", width=600, height=400)
fig2.update_xaxes(categoryorder="total ascending")
fig2.show()

In [23]:
fig3 = px.bar(course_mode_df, x="mode", y="course_mode", color="course", width=600, height=400)
fig3.show()